export type ChartConfigItem = {
  header: string;
  topic: string;
  body: string;
  displayType: string | string[];
  typeDisplay?: string;
  idKey?: string | string[];
  valueKey?: string | string[];
  showLegend?: boolean;
  detailsLink?: string;
  loaded: boolean;
};

export const ChartConfig: ChartConfigItem[] = [
  {
    header: "Apex Class",
    topic: "ApexClass",
    body: "Blueprints for Apex objects.",
    displayType: ["DonutChart"],
    typeDisplay: "Packages",
    idKey: "NamespacePrefix",
    loaded: true,
  },
  {
    header: "Triggers",
    topic: "apexTriggers",
    body: "Custom actions for record changes.",
    displayType: ["DonutChart"],
    typeDisplay: "Packages",
    idKey: "NamespacePrefix",
    loaded: true,
  },
  {
    header: "Apex Batch Jobs",
    topic: "apexBatchJobs",
    body: "Executes operations asynchronously.",
    displayType: ["DonutChart"],
    detailsLink: "/details",
    loaded: false,
  },
  {
    header: "Aura Bundles",
    topic: "auraBundles",
    body: "A bundle contains a Lightning Aura component definition and all its related resources..",
    displayType: ["DonutChart"],
    typeDisplay: "Packages",
    idKey: "NamespacePrefix",
    loaded: true,
  },
  {
    header: "Custom Objects",
    topic: "customObjects",
    body: "User-defined data storage objects.",
    displayType: ["DonutChart"],
    typeDisplay: "States",
    idKey: "ManageableState",
    loaded: true,
  },
  {
    header: "Standard Objects",
    topic: "sobjects",
    body: "Standard data storage objects.",
    displayType: ["DonutChart"],
    typeDisplay: "States",
    idKey: "ManageableState",
    loaded: true,
  },
  {
    header: "Reports",
    topic: "reports",
    body: "Reports a set of data that meets certain criteria, displayed in an organized way",
    displayType: ["DonutChart"],
    idKey: "NamespacePrefix",
    loaded: false,
  },
  {
    header: "Limits Usage",
    topic: "limits",
    body: "Tracks API request usage.",
    displayType: ["StackedBarChart"],
    idKey: [
      "DailyApiRequests",
      "FileStorageMB",
      "DataStorageMB",
      "DailyWorkflowEmails",
    ],
    valueKey: ["Used", "Remaining"],
    loaded: true,
  },
  {
    header: "Workflows",
    topic: "workFlows",
    body: "Automates business processes.",
    displayType: ["DonutChart"],
    typeDisplay: "States",
    idKey: "ManageableState",
    loaded: true,
  },
  {
    header: "Workflows Rules",
    topic: "workFlowRules",
    body: "Defines workflow criteria.",
    displayType: ["DonutChart"],
    typeDisplay: "Packages",
    idKey: "NamespacePrefix",
    loaded: true,
  },
  {
    header: "Workflows Definitions",
    topic: "flowDefinitions",
    body: "Defines workflow logic.",
    displayType: ["DonutChart"],
    typeDisplay: "Packages",
    idKey: "NamespacePrefix",
    loaded: true,
  },
  {
    header: "Flow Test Coverage",
    topic: "flowTestCoverage",
    body: "Measures flow test coverage.",
    displayType: "totalSize",
    // detailsLink: "/details",
    loaded: false,
  },
  {
    header: "Connected Applications",
    topic: "connectedApplications",
    body: "Integrates with external apps.",
    displayType: "totalSize",
    detailsLink: "/details",
    loaded: false,
  },
  {
    header: "External Data Sources",
    topic: "externalDataSource",
    body: "Connects to external data.",
    displayType: "totalSize",
    detailsLink: "/details",
    loaded: false,
  },
  // {
  //   header: "External Services",
  //   topic: "externalDataSource",
  //   body: "Integrates with external services.",
  //   displayValue: "totalSize",
  //   detailsLink: "/details",
  //   loaded: false,
  // },
  {
    header: "External Services",
    topic: "externalService",
    body: "Connects to external services.",
    displayType: "totalSize",
    detailsLink: "/details",
    loaded: false,
  },
  {
    header: "Active Users",
    topic: "activeUsers",
    body: "Tracks active user count.",
    displayType: "totalSize",
    detailsLink: "/details",
    loaded: false,
  },
  {
    header: "VisualForce Pages",
    topic: "visualForcePages",
    body: "User interfaces built with VisualForce.",
    displayType: ["DonutChart"],
    typeDisplay: "Packages",
    idKey: "NamespacePrefix",
    loaded: true,
  },
  {
    header: "Lightning Components",
    topic: "lightningComponents",
    body: "User interfaces built with Lightning.",
    displayType: "totalSize",
    detailsLink: "/details",
    loaded: false,
  },
  {
    header: "Installed Apps",
    topic: "installedApps",
    body: "Tracks installed apps.",
    displayType: "totalSize",
    detailsLink: "/details",
    loaded: false,
  },
  {
    header: "User Licenses",
    topic: "UserLicenses",
    body: "Tracks user license types.",
    displayType: "",
    detailsLink: "/licenses",
    loaded: false,
  },
  {
    header: "Files",
    topic: "contentList",
    body: "Tracks file and content counts.",
    displayType: "totalSize",
    // detailsLink: "/details",
    loaded: false,
  },
  {
    header: "Attachments",
    topic: "attachments",
    body: "User attached files",
    displayType: "totalSize",
    // detailsLink: "/details",
    loaded: false,
  },
  {
    header: "Record Counts",
    topic: "sObjectsRecordCount",
    body: "Tracks record counts per object.",
    displayType: "totalRecords",
    // detailsLink: "/details",
    loaded: false,
  },
  {
    header: "Validation Rules",
    topic: "validationRules",
    body: "Enforces data validation rules.",
    displayType: ["totalSize"],
    detailsLink: "/details",
    loaded: false,
  },
  {
    header: "Email Templates",
    topic: "emailTemplates",
    body: "Predefined email content templates.",
    displayType: ["totalSize"],
    detailsLink: "/details",
    loaded: false,
  },
];
