export type DashboardConfigItem = {
  header: string;
  topic: string;
  body: string;
  displayValue: string | string[];
  detailsLink?: string;
  loaded: boolean;
};

export const dashboardConfig: DashboardConfigItem[] = [
  {
    header: "Apex Class",
    topic: "ApexClass",
    body: "Blueprints for Apex objects.",
    displayValue: ["totalSize"],
    detailsLink: "/details",
    loaded: false,
  },
  {
    header: "Apex Code Coverage",
    topic: "apexCodeCoverage",
    body: "Indicates test coverage for Apex code.",
    displayValue: ["CoveragePercent"],
    // detailsLink: "/details",
    loaded: false,
  },
  {
    header: "Apex Triggers",
    topic: "apexTriggers",
    body: "Custom actions for record changes.",
    displayValue: ["totalSize"],
    detailsLink: "/details",
    loaded: false,
  },
  {
    header: "Apex Batch Jobs",
    topic: "apexBatchJobs",
    body: "Executes operations asynchronously.",
    displayValue: ["totalSize"],
    detailsLink: "/details",
    loaded: false,
  },
  {
    header: "Aura Bundles",
    topic: "auraBundles",
    body: "A bundle contains a Lightning Aura component definition and all its related resources..",
    displayValue: ["totalSize"],
    detailsLink: "/details",
    loaded: false,
  },
  {
    header: "Custom Objects",
    topic: "customObjects",
    body: "User-defined data storage objects.",
    displayValue: ["totalSize"],
    detailsLink: "/details",
    loaded: false,
  },
  {
    header: "Standard Objects",
    topic: "sobjects",
    body: "Standard data storage objects.",
    displayValue: ["totalSize"],
    detailsLink: "/details",
    loaded: false,
  },
  // {
  //   header: "Custom Fields",
  //   topic: "customFields",
  //   body: "User-defined data fields.",
  //   displayValue: ["totalSize"],
  //   detailsLink: "/details",
  //   loaded: false,
  // },
  {
    header: "Custom Fields",
    topic: "CustomField",
    body: "User-defined data fields.",
    displayValue: ["totalSize"],
    detailsLink: "/details",
    loaded: false,
  },
  {
    header: "Custom Field Indexes",
    topic: "customFieldindex",
    body: "Improves query performance.",
    displayValue: ["totalSize"],
    detailsLink: "/details",
    loaded: false,
  },
  {
    header: "Reports",
    topic: "reports",
    body: "Reports a set of data that meets certain criteria, displayed in an organized way",
    displayValue: ["totalSize"],
    detailsLink: "/details",
    loaded: false,
  },
  {
    header: "API Usage",
    topic: "limits",
    body: "Tracks API request usage.",
    displayValue: "DailyApiRequests.UsedPercentage",
    // detailsLink: "/details",
    loaded: false,
  },
  {
    header: "Workflows",
    topic: "workFlows",
    body: "Automates business processes.",
    displayValue: "totalSize",
    detailsLink: "/details",
    loaded: false,
  },
  {
    header: "Workflows Rules",
    topic: "workFlowRules",
    body: "Defines workflow criteria.",
    displayValue: "totalSize",
    detailsLink: "/details",
    loaded: false,
  },
  {
    header: "Workflows Definitions",
    topic: "flowDefinitions",
    body: "Defines workflow logic.",
    displayValue: "totalSize",
    detailsLink: "/details",
    loaded: false,
  },
  {
    header: "Flow Test Coverage",
    topic: "flowTestCoverage",
    body: "Measures flow test coverage.",
    displayValue: "totalSize",
    // detailsLink: "/details",
    loaded: false,
  },
  {
    header: "Connected Applications",
    topic: "connectedApplications",
    body: "Integrates with external apps.",
    displayValue: "totalSize",
    detailsLink: "/details",
    loaded: false,
  },
  {
    header: "External Data Sources",
    topic: "externalDataSource",
    body: "Connects to external data.",
    displayValue: "totalSize",
    detailsLink: "/details",
    loaded: false,
  },
  // {
  //   header: "External Services",
  //   topic: "externalDataSource",
  //   body: "Integrates with external services.",
  //   displayValue: "totalSize",
  //   detailsLink: "/details",
  //   loaded: false,
  // },
  {
    header: "External Services",
    topic: "externalService",
    body: "Connects to external services.",
    displayValue: "totalSize",
    detailsLink: "/details",
    loaded: false,
  },
  {
    header: "Active Users",
    topic: "activeUsers",
    body: "Tracks active user count.",
    displayValue: "totalSize",
    detailsLink: "/details",
    loaded: false,
  },
  {
    header: "VisualForce Pages",
    topic: "visualForcePages",
    body: "User interfaces built with VisualForce.",
    displayValue: "totalSize",
    detailsLink: "/details",
    loaded: false,
  },
  {
    header: "Lightning Components",
    topic: "lightningComponents",
    body: "User interfaces built with Lightning.",
    displayValue: "totalSize",
    detailsLink: "/details",
    loaded: false,
  },
  {
    header: "Installed Apps",
    topic: "installedApps",
    body: "Tracks installed apps.",
    displayValue: "totalSize",
    detailsLink: "/details",
    loaded: false,
  },
  {
    header: "User Licenses",
    topic: "UserLicenses",
    body: "Tracks user license types.",
    displayValue: "",
    detailsLink: "/licenses",
    loaded: true,
  },
  {
    header: "Files",
    topic: "contentList",
    body: "Tracks file and content counts.",
    displayValue: "totalSize",
    // detailsLink: "/details",
    loaded: false,
  },
  {
    header: "Attachments",
    topic: "attachments",
    body: "User attached files",
    displayValue: "totalSize",
    // detailsLink: "/details",
    loaded: false,
  },
  {
    header: "Record Counts",
    topic: "sObjectsRecordCount",
    body: "Tracks record counts per object.",
    displayValue: "totalRecords",
    // detailsLink: "/details",
    loaded: false,
  },
  {
    header: "Validation Rules",
    topic: "validationRules",
    body: "Enforces data validation rules.",
    displayValue: ["totalSize"],
    detailsLink: "/details",
    loaded: false,
  },
  {
    header: "Email Templates",
    topic: "emailTemplates",
    body: "Predefined email content templates.",
    displayValue: ["totalSize"],
    detailsLink: "/details",
    loaded: false,
  },
];
