export const entityMapping = [
  {
    id: "Sales Cloud",
    data: { label: "Sales Cloud" },
    hidden: false,
    type: "vertical",
  },
  {
    id: "Service Cloud",
    data: { label: "Service Cloud" },
    hidden: false,
    type: "vertical",
  },
  {
    id: "Field Service",
    data: { label: "Field Service" },
    hidden: false,
    type: "vertical",
  },
  {
    id: "Marketing Cloud",
    data: { label: "Marketing Cloud" },
    hidden: false,
    type: "vertical",
  },
  {
    id: "Commerce Cloud",
    data: { label: "Commerce Cloud" },
    hidden: false,
    type: "vertical",
  },
  {
    id: "CPQ",
    data: { label: "CPQ" },
    hidden: false,
    type: "vertical",
  },
  {
    id: "Pardot",
    data: { label: "Pardot" },
    hidden: false,
    type: "vertical",
  },
  {
    id: "Community Cloud",
    data: { label: "Community Cloud" },
    hidden: false,
    type: "vertical",
  },
  {
    id: "Nonprofit Cloud",
    data: { label: "Nonprofit Cloud" },
    hidden: false,
    type: "vertical",
  },
  {
    id: "Customer 360",
    data: { label: "Customer 360" },
    hidden: false,
    type: "horizontal",
  },
  {
    id: "Analytics Cloud",
    data: { label: "Analytics Cloud" },
    hidden: false,
    type: "horizontal",
  },
  {
    id: "Einstein",
    data: { label: "Einstein" },
    hidden: false,
    type: "horizontal",
  },
  {
    id: "IoT Cloud",
    data: { label: "IoT Cloud" },
    hidden: false,
    type: "vertical",
  },
  {
    id: "Platform",
    data: { label: "Platform" },
    hidden: false,
    type: "horizontal",
  },
  {
    id: "Account",
    data: { label: "Account", source: "Account" },
    parentId: "Sales Cloud",
    hidden: false,
    extent: "parent",
  },
  {
    id: "Contact",
    data: { label: "Contact", source: "Contact" },
    parentId: "Sales Cloud",
    hidden: false,
    extent: "parent",
  },
  {
    id: "Lead",
    data: { label: "Lead", source: "Lead" },
    parentId: "Sales Cloud",
    hidden: false,
    extent: "parent",
  },
  {
    id: "Opportunity",
    data: { label: "Opportunity", source: "Opportunity" },
    parentId: "Sales Cloud",
    hidden: false,
    extent: "parent",
  },
  {
    id: "Territory",
    data: { label: "Territory", source: "Territory" },
    parentId: "Sales Cloud",
    hidden: false,
    extent: "parent",
  },
  {
    id: "Campaign",
    data: { label: "Campaign", source: "Campaign" },
    parentId: "Sales Cloud",
    hidden: false,
    extent: "parent",
  },
  {
    id: "Product",
    data: { label: "Product", source: "Product" },
    parentId: "Sales Cloud",
    hidden: false,
    extent: "parent",
  },
  {
    id: "PriceBook",
    data: { label: "PriceBook", source: "PriceBook" },
    parentId: "Sales Cloud",
    hidden: false,
    extent: "parent",
  },
  {
    id: "Quote",
    data: { label: "Quote", source: "Quote" },
    parentId: "Sales Cloud",
    hidden: false,
    extent: "parent",
  },
  {
    id: "Contract",
    data: { label: "Contract", source: "Contract" },
    parentId: "Sales Cloud",
    hidden: false,
    extent: "parent",
  },
  {
    id: "Order",
    data: { label: "Order", source: "Order" },
    parentId: "Sales Cloud",
    hidden: false,
    extent: "parent",
  },
  {
    id: "Competitor",
    data: { label: "Competitor", source: "Competitor" },
    parentId: "Sales Cloud",
    hidden: false,
    extent: "parent",
  },
  {
    id: "Case",
    data: { label: "Case", source: "Case" },
    parentId: "Service Cloud",
    hidden: false,
    extent: "parent",
  },
  {
    id: "Solution",
    data: { label: "Solution", source: "Solution" },
    parentId: "Service Cloud",
    hidden: false,
    extent: "parent",
  },
  {
    id: "Asset",
    data: { label: "Asset", source: "Asset" },
    parentId: "Service Cloud",
    hidden: false,
    extent: "parent",
  },
  {
    id: "Entitlement",
    data: { label: "Entitlement", source: "Entitlement" },
    parentId: "Service Cloud",
    hidden: false,
    extent: "parent",
  },
  {
    id: "ServiceContract",
    data: { label: "ServiceContract", source: "ServiceContract" },
    parentId: "Service Cloud",
    hidden: false,
    extent: "parent",
  },
  {
    id: "WorkOrder",
    data: { label: "WorkOrder", source: "WorkOrder" },
    parentId: "Service Cloud",
    hidden: false,
    extent: "parent",
  },
  {
    id: "KnowledgeArticle",
    data: { label: "KnowledgeArticle", source: "KnowledgeArticle" },
    parentId: "Service Cloud",
    hidden: false,
    extent: "parent",
  },
  {
    id: "LiveChatTranscript",
    data: { label: "LiveChatTranscript", source: "LiveChatTranscript" },
    parentId: "Service Cloud",
    hidden: false,
    extent: "parent",
  },
  {
    id: "Macros",
    data: { label: "Macros", source: "Macros" },
    parentId: "Service Cloud",
    hidden: false,
    extent: "parent",
  },
  {
    id: "Campaign",
    data: { label: "Campaign", source: "Campaign" },
    parentId: "Marketing Cloud",
    hidden: false,
    extent: "parent",
  },
  {
    id: "CampaignMember",
    data: { label: "Campaign Member", source: "CampaignMember" },
    parentId: "Marketing Cloud",
    hidden: false,
    extent: "parent",
  },

  {
    id: "Lead",
    data: { label: "Lead", source: "Lead" },
    parentId: "Marketing Cloud",
    hidden: false,
    extent: "parent",
  },

  {
    id: "MarketingAsset",
    data: { label: "Marketing Asset", source: "MarketingAsset" },
    parentId: "Marketing Cloud",
    hidden: false,
    extent: "parent",
  },

  {
    id: "Journey",
    data: { label: "Journey", source: "Journey" },
    parentId: "Marketing Cloud",
    hidden: false,
    extent: "parent",
  },

  {
    id: "EmailTemplate",
    data: { label: "Email Template", source: "EmailTemplate" },
    parentId: "Marketing Cloud",
    hidden: false,
    extent: "parent",
  },

  {
    id: "Community",
    data: { label: "Community", source: "Community" },
    parentId: "Community Cloud",
    hidden: false,
    extent: "parent",
  },

  {
    id: "Question",
    data: { label: "Question", source: "Question" },
    parentId: "Community Cloud",
    hidden: false,
    extent: "parent",
  },
  {
    id: "Answer",
    data: { label: "Answer", source: "Answer" },
    parentId: "Community Cloud",
    hidden: false,
    extent: "parent",
  },
  {
    id: "Idea",
    data: { label: "Idea", source: "Idea" },
    parentId: "Community Cloud",
    hidden: false,
    extent: "parent",
  },
  {
    id: "IdeaComment",
    data: { label: "Idea Comment", source: "IdeaComment" },
    parentId: "Community Cloud",
    hidden: false,
    extent: "parent",
  },
  {
    id: "Sites",
    data: { label: "Site", source: "Site" },
    parentId: "Community Cloud",
    hidden: false,
    extent: "parent",
  },
  {
    id: "Network",
    data: { label: "Network", source: "Network" },
    parentId: "Community Cloud",
    hidden: false,
    extent: "parent",
  },
  {
    id: "ProcessDefinition",
    data: { label: "Process Definition", source: "ProcessDefinition" },
    parentId: "Community Cloud",
    hidden: false,
    extent: "parent",
  },

  {
    id: "WorkOrder",
    data: { label: "Work Order", source: "WorkOrder" },
    parentId: "Field Service",
    hidden: false,
    extent: "parent",
  },
  {
    id: "ServiceAppointment",
    data: { label: "Appointment", source: "ServiceAppointment" },
    parentId: "Field Service",
    hidden: false,
    extent: "parent",
  },
  {
    id: "ServiceResource",
    data: { label: "Resource", source: "ServiceResource" },
    parentId: "Field Service",
    hidden: false,
    extent: "parent",
  },
  {
    id: "ServiceTerritory",
    data: { label: "Territory", source: "ServiceTerritory" },
    parentId: "Field Service",
    hidden: false,
    extent: "parent",
  },
  {
    id: "ProductRequired",
    data: { label: "Product Required", source: "ProductRequired" },
    parentId: "Field Service",
    hidden: false,
    extent: "parent",
  },
  {
    id: "ProductConsumed",
    data: { label: "ProductConsumed", source: "ProductConsumed" },
    parentId: "Field Service",
    hidden: false,
    extent: "parent",
  },
  {
    id: "Order",
    data: { label: "Order", source: "Order" },
    parentId: "Commerce Cloud",
    hidden: false,
    extent: "parent",
  },
  {
    id: "PriceBookEntry",
    data: { label: "Custom Price Book", source: "WebStorePriceBook" },
    parentId: "Commerce Cloud",
    hidden: false,
    extent: "parent",
  },
  {
    id: "OrderItem",
    data: { label: "OrderItem", source: "OrderItem" },
    parentId: "Commerce Cloud",
    hidden: false,
    extent: "parent",
  },
  {
    id: "Product",
    data: { label: "Product", source: "Product" },
    parentId: "Commerce Cloud",
    hidden: false,
    extent: "parent",
  },
  {
    id: "PriceBook",
    data: { label: "PriceBook", source: "PriceBook" },
    parentId: "Commerce Cloud",
    hidden: false,
    extent: "parent",
  },
  {
    id: "Cart",
    data: { label: "Cart", source: "Cart" },
    parentId: "Commerce Cloud",
    hidden: false,
    extent: "parent",
  },
  {
    id: "CartItem",
    data: { label: "CartItem", source: "CartItem" },
    parentId: "Commerce Cloud",
    hidden: false,
    extent: "parent",
  },
  {
    id: "Store",
    data: { label: "Store", source: "WebStore" },
    parentId: "Commerce Cloud",
    hidden: false,
    extent: "parent",
  },
  {
    id: "PaymentMethod",
    data: { label: "Payment Method", source: "PaymentMethod" },
    parentId: "Commerce Cloud",
    hidden: false,
    extent: "parent",
  },
  {
    id: "Promotion",
    data: { label: "Promotion", source: "Promotion" },
    parentId: "Commerce Cloud",
    hidden: false,
    extent: "parent",
  },
  {
    id: "Store Catalog",
    data: { label: "Store Catalog", source: "WebStoreCatalog" },
    parentId: "Commerce Cloud",
    hidden: false,
    extent: "parent",
  },
  {
    id: "Product Catalog",
    data: { label: "Product Catalog", source: "ProductCatalog" },
    parentId: "Commerce Cloud",
    hidden: false,
    extent: "parent",
  },
  {
    id: "Product Media",
    data: { label: "Product Media", source: "ProductMedia" },
    parentId: "Commerce Cloud",
    hidden: false,
    extent: "parent",
  },

  {
    id: "SBQQ__Quote__c",
    data: { label: "Quote", source: "SBQQ__Quote__c" },
    parentId: "CPQ",
    hidden: false,
    extent: "parent",
  },
  {
    id: "SBQQ__QuoteLine__c",
    data: { label: "Quote Line", source: "SBQQ__QuoteLine__c" },
    parentId: "CPQ",
    hidden: false,
    extent: "parent",
  },
  {
    id: "SBQQ__ProductRule__c",
    data: { label: "Product Rule", source: "SBQQ__ProductRule__c" },
    parentId: "CPQ",
    hidden: false,
    extent: "parent",
  },
  {
    id: "SBQQ__PriceRule__c",
    data: { label: "Price Rule", source: "SBQQ__PriceRule__c" },
    parentId: "CPQ",
    hidden: false,
    extent: "parent",
  },
  {
    id: "Prospect",
    data: { label: "Prospect", source: "Prospect" },
    parentId: "Pardot",
    hidden: false,
    extent: "parent",
  },

  {
    id: "Visitor",
    data: { label: "Visitor", source: "Visitor" },
    parentId: "Pardot",
    hidden: false,
    extent: "parent",
  },
  {
    id: "Visit",
    data: { label: "Visit", source: "Visit" },
    parentId: "Pardot",
    hidden: false,
    extent: "parent",
  },
  {
    id: "PardotCampaign",
    data: { label: "PardotCampaign", source: "PardotCampaign" },
    parentId: "Pardot",
    hidden: false,
    extent: "parent",
  },
  {
    id: "npe01__Contact_Donation__c",
    data: { label: "Contact Donation", source: "npe01__Contact_Donation__c" },
    parentId: "Nonprofit Cloud",
    hidden: false,
    extent: "parent",
  },
  {
    id: "npsp__Recurring_Donation__c",
    data: {
      label: "Recurring Donation",
      source: "npsp__Recurring_Donation__c",
    },
    parentId: "Nonprofit Cloud",
    hidden: false,
    extent: "parent",
  },
  {
    id: "npsp__Engagement_Plan__c",
    data: {
      label: "Engagement Plan",
      source: "npsp__Engagement_Plan__c",
    },
    parentId: "Nonprofit Cloud",
    hidden: false,
    extent: "parent",
  },
  {
    id: "npsp__General_Accounting_Unit__c",
    data: {
      label: "General Accounting Unit",
      source: "npsp__General_Accounting_Unit__c",
    },
    parentId: "Nonprofit Cloud",
    hidden: false,
    extent: "parent",
  },
  {
    id: "AIApplication",
    data: {
      label: "AI Application",
      source: "AIApplication",
    },
    parentId: "Einstein",
    hidden: false,
    extent: "parent",
  },
  {
    id: "AIModelMetric",
    data: {
      label: "AI Model Metric",
      source: "AIModelMetric",
    },
    parentId: "Einstein",
    hidden: false,
    extent: "parent",
  },
  {
    id: "MLPredictionDefinition",
    data: {
      label: "Prediction Definitions",
      source: "MLPredictionDefinition",
    },
    parentId: "Einstein",
    hidden: false,
    extent: "parent",
  },
  // {
  //   id: "Prompt",
  //   data: {
  //     label: "Prompt",
  //     source: "Prompt",
  //   },
  //   parentId: "Einstein",
  //   hidden: false,
  //   extent: "parent",
  // },
  // {
  //   id: "PromptAction",
  //   data: {
  //     label: "Prompt Action",
  //     source: "PromptAction",
  //   },
  //   parentId: "Einstein",
  //   hidden: false,
  //   extent: "parent",
  // },

  {
    id: "IoTDevice",
    data: {
      label: "Devices",
      source: "IoTDevice",
    },
    parentId: "IoT Cloud",
    hidden: false,
    extent: "parent",
  },
  {
    id: "IoTDeviceEvent",
    data: {
      label: "Device Event",
      source: "IoTDeviceEvent",
    },
    parentId: "IoT Cloud",
    hidden: false,
    extent: "parent",
  },
  {
    id: "IoTOrchestrationInstance",
    data: {
      label: "Orchestration Instance",
      source: "IoTOrchestrationInstance",
    },
    parentId: "IoT Cloud",
    hidden: false,
    extent: "parent",
  },
  {
    id: "User",
    data: {
      label: "User",
      source: "User",
    },
    parentId: "Platform",
    hidden: false,
    extent: "parent",
  },
  {
    id: "Profile",
    data: {
      label: "Profile",
      source: "Profile",
    },
    parentId: "Platform",
    hidden: false,
    extent: "parent",
  },
  {
    id: "Role",
    data: {
      label: "Role",
      source: "Role",
    },
    parentId: "Platform",
    hidden: false,
    extent: "parent",
  },
  {
    id: "Group",
    data: {
      label: "Group",
      source: "Group",
    },
    parentId: "Platform",
    hidden: false,
    extent: "parent",
  },
  {
    id: "Queue",
    data: {
      label: "Queue",
      source: "Queue",
    },
    parentId: "Platform",
    hidden: false,
    extent: "parent",
  },
  {
    id: "Task",
    data: {
      label: "Task",
      source: "Task",
    },
    parentId: "Platform",
    hidden: false,
    extent: "parent",
  },
  {
    id: "Event",
    data: {
      label: "Event",
      source: "Event",
    },
    parentId: "Platform",
    hidden: false,
    extent: "parent",
  },
  {
    id: "Note",
    data: {
      label: "Note",
      source: "Note",
    },
    parentId: "Platform",
    hidden: false,
    extent: "parent",
  },
  {
    id: "Attachment",
    data: {
      label: "Attachment",
      source: "Attachment",
    },
    parentId: "Platform",
    hidden: false,
    extent: "parent",
  },
  {
    id: "Document",
    data: {
      label: "Document",
      source: "Task",
    },
    parentId: "Platform",
    hidden: false,
    extent: "parent",
  },
  {
    id: "CustomObject",
    data: {
      label: "CustomObject",
      source: "CustomObject",
    },
    parentId: "Platform",
    hidden: false,
    extent: "parent",
  },
  {
    id: "Topic",
    data: { label: "Chatter", source: "Topic" },
    parentId: "Platform",
    hidden: false,
    extent: "parent",
  },
  {
    id: "Individual",
    data: {
      label: "Individual",
      source: "Individual",
    },
    parentId: "Customer 360",
    hidden: false,
    extent: "parent",
  },
  {
    id: "DataUsePurpose",
    data: {
      label: "Data Use Purpose",
      source: "DataUsePurpose",
    },
    parentId: "Customer 360",
    hidden: false,
    extent: "parent",
  },
  {
    id: "DataUseLegalBasis",
    data: {
      label: "Data Use Legal Basis",
      source: "DataUseLegalBasis",
    },
    parentId: "Customer 360",
    hidden: false,
    extent: "parent",
  },
  {
    id: "ContactPointTypeConsent",
    data: {
      label: "Contact Point Type Consent",
      source: "ContactPointTypeConsent",
    },
    parentId: "Customer 360",
    hidden: false,
    extent: "parent",
  },
  {
    id: "Dashboard",
    data: {
      label: "Dashboard",
      source: "Dashboard",
    },
    parentId: "Analytics Cloud",
    hidden: false,
    extent: "parent",
  },
  {
    id: "Lens",
    data: {
      label: "Lens",
      source: "Lens",
    },
    parentId: "Analytics Cloud",
    hidden: false,
    extent: "parent",
  },
  {
    id: "Dataset",
    data: {
      label: "Dataset",
      source: "Dataset",
    },
    parentId: "Analytics Cloud",
    hidden: false,
    extent: "parent",
  },
  {
    id: "Report",
    data: {
      label: "Report",
      source: "Report",
    },
    parentId: "Analytics Cloud",
    hidden: false,
    extent: "parent",
  },
  {
    id: "ReportType",
    data: {
      label: "ReportType",
      source: "ReportType",
    },
    parentId: "Analytics Cloud",
    hidden: false,
    extent: "parent",
  },
];
