export const functionalUsage = [
  {
    id: "Sales Cloud",
    data: { label: "Sales Cloud" },
    hidden: false,
    type: "vertical",
  },
  {
    id: "Service Cloud",
    data: { label: "Service Cloud" },
    hidden: false,
    type: "vertical",
  },
  {
    id: "Field Service",
    data: { label: "Field Service" },
    hidden: false,
    type: "vertical",
  },
  {
    id: "Marketing Cloud",
    data: { label: "Marketing Cloud" },
    hidden: false,
    type: "vertical",
  },
  {
    id: "Commerce Cloud",
    data: { label: "Commerce Cloud" },
    hidden: false,
    type: "vertical",
  },
  {
    id: "CPQ",
    data: { label: "CPQ" },
    hidden: false,
    type: "vertical",
  },
  {
    id: "Pardot",
    data: { label: "Pardot" },
    hidden: false,
    type: "vertical",
  },
  {
    id: "Community Cloud",
    data: { label: "Community Cloud" },
    hidden: false,
    type: "vertical",
  },
  {
    id: "Nonprofit Cloud",
    data: { label: "Nonprofit Cloud" },
    hidden: false,
    type: "vertical",
  },
  {
    id: "Customer 360",
    data: { label: "Customer 360" },
    hidden: false,
    type: "horizontal",
  },
  {
    id: "Analytics Cloud",
    data: { label: "Analytics Cloud" },
    hidden: false,
    type: "horizontal",
  },
  {
    id: "Einstien",
    data: { label: "Einstien" },
    hidden: false,
    type: "horizontal",
  },
  {
    id: "IoT Cloud",
    data: { label: "IoT Cloud" },
    hidden: false,
    type: "vertical",
  },
  {
    id: "Platform",
    data: { label: "Platform" },
    hidden: false,
    type: "horizontal",
  },
  {
    id: "Account",
    data: { label: "Account", source: "Account" },
    parentId: "Sales Cloud",
    hidden: false,
    extent: "parent",
  },
  {
    id: "Contact",
    data: { label: "Contact", source: "Contact" },
    parentId: "Sales Cloud",
    hidden: false,
    extent: "parent",
  },
  {
    id: "Lead",
    data: { label: "Lead", source: "Lead" },
    parentId: "Sales Cloud",
    hidden: false,
    extent: "parent",
  },
  {
    id: "Opportunity",
    data: { label: "Opportunity", source: "Opportunity" },
    parentId: "Sales Cloud",
    hidden: false,
    extent: "parent",
  },
  {
    id: "Campaign",
    data: { label: "Campaign", source: "Campaign" },
    parentId: "Sales Cloud",
    hidden: false,
    extent: "parent",
  },
  {
    id: "Product",
    data: { label: "Product", source: "Product" },
    parentId: "Sales Cloud",
    hidden: false,
    extent: "parent",
  },
  {
    id: "PriceBook",
    data: { label: "PriceBook", source: "PriceBook" },
    parentId: "Sales Cloud",
    hidden: false,
    extent: "parent",
  },
  {
    id: "Quote",
    data: { label: "Quote", source: "Quote" },
    parentId: "Sales Cloud",
    hidden: false,
    extent: "parent",
  },
  {
    id: "Contract",
    data: { label: "Contract", source: "Contract" },
    parentId: "Sales Cloud",
    hidden: false,
    extent: "parent",
  },
  {
    id: "Order",
    data: { label: "Order", source: "Order" },
    parentId: "Sales Cloud",
    hidden: false,
    extent: "parent",
  },
  {
    id: "Competitor",
    data: { label: "Competitor", source: "Competitor" },
    parentId: "Sales Cloud",
    hidden: false,
    extent: "parent",
  },
  {
    id: "Case",
    data: { label: "Case", source: "Case" },
    parentId: "Service Cloud",
    hidden: false,
    extent: "parent",
  },
  {
    id: "Solution",
    data: { label: "Solution", source: "Solution" },
    parentId: "Service Cloud",
    hidden: false,
    extent: "parent",
  },
  {
    id: "Asset",
    data: { label: "Asset", source: "Asset" },
    parentId: "Service Cloud",
    hidden: false,
    extent: "parent",
  },
  {
    id: "Entitlement",
    data: { label: "Entitlement", source: "Entitlement" },
    parentId: "Service Cloud",
    hidden: false,
    extent: "parent",
  },
  {
    id: "ServiceContract",
    data: { label: "ServiceContract", source: "ServiceContract" },
    parentId: "Service Cloud",
    hidden: false,
    extent: "parent",
  },
  {
    id: "WorkOrder",
    data: { label: "WorkOrder", source: "WorkOrder" },
    parentId: "Service Cloud",
    hidden: false,
    extent: "parent",
  },
  {
    id: "KnowledgeArticle",
    data: { label: "KnowledgeArticle", source: "KnowledgeArticle" },
    parentId: "Service Cloud",
    hidden: false,
    extent: "parent",
  },
  {
    id: "LiveChatTranscript",
    data: { label: "LiveChatTranscript", source: "LiveChatTranscript" },
    parentId: "Service Cloud",
    hidden: false,
    extent: "parent",
  },
  {
    id: "Macros",
    data: { label: "Macros", source: "Macros" },
    parentId: "Service Cloud",
    hidden: false,
    extent: "parent",
  },
  {
    id: "Campaign",
    data: { label: "Campaign", source: "Campaign" },
    parentId: "Marketing Cloud",
    hidden: false,
    extent: "parent",
  },
  {
    id: "CampaignMember",
    data: { label: "Campaign Member", source: "CampaignMember" },
    parentId: "Marketing Cloud",
    hidden: false,
    extent: "parent",
  },

  {
    id: "Lead",
    data: { label: "Lead", source: "Lead" },
    parentId: "Marketing Cloud",
    hidden: false,
    extent: "parent",
  },

  {
    id: "MarketingAsset",
    data: { label: "Marketing Asset", source: "MarketingAsset" },
    parentId: "Marketing Cloud",
    hidden: false,
    extent: "parent",
  },

  {
    id: "Journey",
    data: { label: "Journey", source: "Journey" },
    parentId: "Marketing Cloud",
    hidden: false,
    extent: "parent",
  },

  {
    id: "EmailTemplate",
    data: { label: "Email Template", source: "EmailTemplate" },
    parentId: "Marketing Cloud",
    hidden: false,
    extent: "parent",
  },

  {
    id: "Community",
    data: { label: "Community", source: "Community" },
    parentId: "Community Cloud",
    hidden: false,
    extent: "parent",
  },

  {
    id: "Topic",
    data: { label: "Topic", source: "Topic" },
    parentId: "Community Cloud",
    hidden: false,
    extent: "parent",
  },

  {
    id: "Question",
    data: { label: "Question", source: "Question" },
    parentId: "Community Cloud",
    hidden: false,
    extent: "parent",
  },
  {
    id: "Answer",
    data: { label: "Answer", source: "Answer" },
    parentId: "Community Cloud",
    hidden: false,
    extent: "parent",
  },
  {
    id: "Idea",
    data: { label: "Idea", source: "Idea" },
    parentId: "Community Cloud",
    hidden: false,
    extent: "parent",
  },
  {
    id: "IdeaComment",
    data: { label: "Idea Comment", source: "IdeaComment" },
    parentId: "Community Cloud",
    hidden: false,
    extent: "parent",
  },

  {
    id: "WorkOrder",
    data: { label: "Work Order", source: "WorkOrder" },
    parentId: "Field Service",
    hidden: false,
    extent: "parent",
  },
  {
    id: "ServiceAppointment",
    data: { label: "Appointment", source: "ServiceAppointment" },
    parentId: "Field Service",
    hidden: false,
    extent: "parent",
  },
  {
    id: "ServiceResource",
    data: { label: "Resource", source: "ServiceResource" },
    parentId: "Field Service",
    hidden: false,
    extent: "parent",
  },
  {
    id: "ServiceTerritory",
    data: { label: "Territory", source: "ServiceTerritory" },
    parentId: "Field Service",
    hidden: false,
    extent: "parent",
  },
  {
    id: "ProductRequired",
    data: { label: "Product Required", source: "ProductRequired" },
    parentId: "Field Service",
    hidden: false,
    extent: "parent",
  },
  {
    id: "ProductConsumed",
    data: { label: "ProductConsumed", source: "ProductConsumed" },
    parentId: "Field Service",
    hidden: false,
    extent: "parent",
  },
  {
    id: "Order",
    data: { label: "Order", source: "Order" },
    parentId: "Commerce Cloud",
    hidden: false,
    extent: "parent",
  },
  {
    id: "Order",
    data: { label: "Order", source: "Order" },
    parentId: "Commerce Cloud",
    hidden: false,
    extent: "parent",
  },
  {
    id: "OrderItem",
    data: { label: "OrderItem", source: "OrderItem" },
    parentId: "Commerce Cloud",
    hidden: false,
    extent: "parent",
  },
  {
    id: "Product",
    data: { label: "Product", source: "Product" },
    parentId: "Commerce Cloud",
    hidden: false,
    extent: "parent",
  },
  {
    id: "PriceBook",
    data: { label: "PriceBook", source: "PriceBook" },
    parentId: "Commerce Cloud",
    hidden: false,
    extent: "parent",
  },
  {
    id: "Cart",
    data: { label: "Cart", source: "Cart" },
    parentId: "Commerce Cloud",
    hidden: false,
    extent: "parent",
  },
  {
    id: "CartItem",
    data: { label: "CartItem", source: "CartItem" },
    parentId: "Commerce Cloud",
    hidden: false,
    extent: "parent",
  },
];
