export interface LicenseConfigItem {
  header: string;
  topic: string;
  group?: string;
  body: string;
  loaded?: boolean;
}

export const licenseConfig: LicenseConfigItem[] = [
  {
    group: "User Licenses",
    topic: "AUL",
    header: "Salesforce Platform",
    body: "A Salesforce platform license provides access to basic CRM functionality and custom application development tools",
  },
  {
    group: "User Licenses",
    topic: "CLOUD_INTEGRATION_USER",
    header: "Cloud Integration User",
    body: "A cloud integration user leverages cloud services to connect and streamline disparate systems and data sources for cohesive operation",
  },
  {
    group: "User Licenses",
    topic: "CSN_External_User",
    header: "Chatter External",
    body: "Chatter External is a cloud-based solution that enables businesses to securely collaborate and communicate with external partners and customers using Salesforce Chatter",
  },
  {
    group: "User Licenses",
    topic: "CSN_User",
    header: "Chatter Free",
    body: "Chatter Free is a communication tool designed to minimize distractions and streamline conversations for increased productivity",
  },
  {
    group: "User Licenses",
    topic: "High_Volume_Customer_Portal_User",
    header: "High Volume Customer Portal",
    body: "A high volume customer portal is a scalable, user-friendly online platform designed to handle and streamline large numbers of customer interactions efficiently",
  },
  {
    group: "User Licenses",
    topic: "INSIGHTS_INTEGRATION_USER",
    header: "Analytics Cloud Integration User",
    body: "An analytics cloud integration user leverages cloud-based tools to connect, analyze, and visualize data from various sources for informed decision-making",
  },
  {
    group: "User Licenses",
    topic: "PID_CHATTER",
    header: "Chatter Only",
    body: "A chatter-only license refers to a limited access level that permits only the ability to engage in conversation or chat within a specified platform or application",
  },
  {
    group: "User Licenses",
    topic: "PID_COMPANY_COMMUNITIES",
    header: "Company Communities",
    body: "Company Communities License: Empowering organizations with structured community management and engagement tools",
  },
  {
    group: "User Licenses",
    topic: "PID_Customer_Community",
    header: "Customer Community",
    body: "A customer community license provides limited access to Salesforce features for external users, facilitating engagement and support",
  },
  {
    group: "User Licenses",
    topic: "PID_Customer_Community_Login",
    header: "Customer Community Login",
    body: "Customer community login license: Access privilege enabling customer interaction and engagement within a designated online community",
  },
  {
    group: "User Licenses",
    topic: "PID_Customer_Community_Plus",
    header: "Customer Community Plus",
    body: "Customer community plus license refers to a software solution that combines customer community management features with licensing capabilities",
  },
  {
    group: "User Licenses",
    topic: "PID_Customer_Community_Plus_Login",
    header: "Customer Community Plus Login",
    body: "Empower your customers with a seamless community experience integrated with secure login capabilities",
  },
  {
    group: "User Licenses",
    topic: "PID_External_Apps_Login",
    header: "External Apps Login",
    body: "External Apps Login License allows external applications to securely access and authenticate users within a system",
  },
  {
    group: "User Licenses",
    topic: "PID_External_Apps_Member",
    header: "External Apps",
    body: "External apps license: Legal terms governing the use and distribution of third-party software integrated with a primary application",
  },
  {
    group: "User Licenses",
    topic: "PID_External_Apps_Plus_Login",
    header: "External Apps Plus Login",
    body: "External applications with login licensing streamline access control and user authentication for enhanced security and user management",
  },
  {
    group: "User Licenses",
    topic: "PID_External_Apps_Plus_Member",
    header: "External Apps Plus",
    body: "External apps are software applications developed by third-party vendors and distributed under specific licensing terms",
  },
  {
    group: "User Licenses",
    topic: "PID_External_Identity",
    header: "External Identity",
    body: "An external identity license allows controlled access and authentication for users outside an organization's direct control",
  },
  {
    group: "User Licenses",
    topic: "PID_Guest_User",
    header: "Guest License",
    body: "A guest license allows temporary access or usage rights typically granted to visitors or temporary users",
  },
  {
    group: "User Licenses",
    topic: "PID_Identity_User",
    header: "Identity",
    body: "An identity license serves as a verified credential confirming a person's identity and personal details",
  },
  {
    group: "User Licenses",
    topic: "PID_Partner_Community",
    header: "Partner Community",
    body: "Partner Community License: Salesforce's license tailored for partners to collaborate and extend Salesforce CRM capabilities",
  },
  {
    group: "User Licenses",
    topic: "PID_Partner_Community_Login",
    header: "Partner Community Login",
    body: "Partner Community Login license enables external partners to access and collaborate within your Salesforce community",
  },
  {
    group: "User Licenses",
    topic: "PID_WCUSER",
    header: "Work.com Only",
    body: "Work.com Only license enables access to Salesforce's Work.com platform, focusing on employee engagement, wellness, and productivity tools",
  },
  {
    group: "User Licenses",
    topic: "SALESFORCE_INTEGRATION_USER",
    header: "Salesforce Integration",
    body: "Salesforce Integration License allows seamless connectivity and data synchronization between Salesforce and external applications",
  },
  {
    group: "User Licenses",
    topic: "SERVICE_CLOUD",
    header: "Service Cloud",
    body: "Service Cloud license enables organizations to deliver personalized customer service experiences across multiple channels and devices",
  },
  {
    group: "User Licenses",
    topic: "SFDC",
    header: "Salesforce",
    body: "A Salesforce license grants users access to Salesforce's cloud-based CRM platform and its suite of business applications",
  },
  {
    header:
      "Experience Cloud: Maximum Content Delivery Network(CDN) Bandwidth in TeraBytes",
    topic: "setting/force.com/orgValue.ExperienceCloudCDNTraffic",
    group: "Usage Entitlements",
    body: "Defines the maximum amount of CDN bandwidth, measured in terabytes, allocated for Experience Cloud sites. This limit helps manage data transfer for your community pages and content.",
  },
  {
    header: "Maximum Next Best Action Requests available",
    topic: "setting/force.com/orgValue.NBAMaxAvailableRequests",
    group: "Usage Entitlements",
    body: "Specifies the maximum number of Next Best Action requests that can be made. This limit affects how many times your org can use Einstein Next Best Action to suggest recommendations and offers.",
  },
  {
    header: "Lightning External Apps Plus Daily Unique Logins",
    topic: "setting/force.com/orgValue.MaxLEAPlusUniqueLogins",
    group: "Usage Entitlements",
    body: "Sets the maximum number of unique daily logins allowed for Lightning External Apps Plus. This controls access for external users to your Lightning apps with enhanced features.",
  },
  {
    header: "Lightning External Apps Daily Unique Logins",
    topic: "setting/force.com/orgValue.MaxLEAUniqueLogins",
    group: "Usage Entitlements",
    body: "Determines the maximum number of unique daily logins permitted for standard Lightning External Apps. This manages access for external users to your basic Lightning apps.",
  },
  {
    header: "Partner Community Members",
    topic: "setting/force.com/orgValue.MaxPartnerNetworkMembers",
    group: "Usage Entitlements",
    body: "Defines the maximum number of partner community members allowed in your Salesforce org. This limits how many external partners can access your partner community.",
  },
  {
    header: "Partner Community Logins",
    topic: "setting/force.com/orgValue.MaxPartnerNetworkLogins",
    group: "Usage Entitlements",
    body: "Sets the maximum number of logins allowed for partner community users. This helps manage the usage and access frequency of your partner community.",
  },
  {
    header: "Internal Community Members",
    topic: "setting/force.com/orgValue.MaxRegularNetworkMembers",
    group: "Usage Entitlements",
    body: "Specifies the maximum number of internal community members allowed. This limits how many of your organization's employees can access internal communities.",
  },
  {
    header: "Customer Community Members",
    topic: "setting/force.com/orgValue.MaxCustomerNetworkMembers",
    group: "Usage Entitlements",
    body: "Defines the maximum number of customer community members permitted. This controls how many customers can access your customer-facing community.",
  },
  {
    header: "Customer Community Logins",
    topic: "setting/force.com/orgValue.MaxCustomerNetworkLogins",
    group: "Usage Entitlements",
    body: "Sets the maximum number of logins allowed for customer community users. This helps manage the usage and access frequency of your customer community.",
  },
  {
    header: "Maximum Public Experience Page Views",
    topic: "setting/force.com/orgValue.MaxPublicNetworkPageViews",
    group: "Usage Entitlements",
    body: "Determines the maximum number of page views allowed for public Experience Cloud sites. This helps manage traffic to your publicly accessible community pages.",
  },
  {
    header: "Maximum number of Salesforce Customer Identity logins",
    topic: "setting/force.com/orgValue.MaxExtIdentityLogins",
    group: "Usage Entitlements",
    body: "Specifies the maximum number of logins allowed using Salesforce Customer Identity. This limits how often external users can authenticate using this service.",
  },
  {
    header: "Customer Community Plus Logins",
    topic: "setting/force.com/orgValue.MaxPowerCustNetworkLogins",
    group: "Usage Entitlements",
    body: "Sets the maximum number of logins allowed for Customer Community Plus users. This manages access for users with extended permissions in your customer community.",
  },
  {
    header: "Customer Community Plus Members",
    topic: "setting/force.com/orgValue.MaxPowerCustNetworkMembers",
    group: "Usage Entitlements",
    body: "Defines the maximum number of Customer Community Plus members allowed. This limits how many customers can have extended access and permissions in your community.",
  },
  {
    header: "Customer Community Plus Daily Unique Logins",
    topic: "setting/force.com/orgValue.MaxPwrCustComUniqueLogins",
    group: "Usage Entitlements",
    body: "Determines the maximum number of unique daily logins for Customer Community Plus users. This helps manage daily access patterns for users with extended permissions.",
  },
  {
    header: "Partner Community Daily Unique Logins",
    topic: "setting/force.com/orgValue.MaxPartnerComUniqueLogins",
    group: "Usage Entitlements",
    body: "Sets the maximum number of unique daily logins for Partner Community users. This helps track and limit daily partner access to your community.",
  },
  {
    header: "Customer Community Daily Unique Logins",
    topic: "setting/force.com/orgValue.MaxCustComUniqueLogins",
    group: "Usage Entitlements",
    body: "Specifies the maximum number of unique daily logins for Customer Community users. This helps manage daily customer access patterns to your community.",
  },
  {
    header: "Maximum Flow Interviews with UI per Month",
    topic: "setting/force.com/orgValue.MaxFlowUiExecutions",
    group: "Usage Entitlements",
    body: "Defines the maximum number of flow interviews with user interface that can be executed per month. This limits how often flows with screen elements can be run.",
  },
  {
    header: "Maximum Paused and Waiting Flow Interviews",
    topic: "setting/force.com/orgValue.MaxWaitingInterviews",
    group: "Usage Entitlements",
    body: "Sets the maximum number of flow interviews that can be paused or in a waiting state at any given time. This helps manage resources for long-running flows.",
  },
  {
    header: "Maximum Flow Interviews Without UI per Month",
    topic: "setting/force.com/orgValue.MaxFlowNonUiExecutions",
    group: "Usage Entitlements",
    body: "Specifies the maximum number of flow interviews without user interface that can be executed per month. This limits how often automated flows can be run.",
  },
  {
    header: "API Request Limit per Month",
    topic: "setting/force.com/orgValue.Provisioned30DayApiRequests",
    group: "Usage Entitlements",
    body: "Defines the maximum number of API requests allowed per month. This helps manage integration and external system interactions with your Salesforce org.",
  },
  {
    header: "Maximum Orchestration Runs",
    topic: "setting/force.com/orgValue.MaxOrchestrationRuns",
    group: "Usage Entitlements",
    body: "Sets the maximum number of orchestration runs allowed. This limits how many times you can execute complex, multi-step business processes in Salesforce.",
  },
  {
    header: "B2B Commerce Total Active Storefronts",
    topic: "setting/force.com/orgValue.B2bcommPkgActiveStorefronts",
    group: "Usage Entitlements",
    body: "Specifies the maximum number of active B2B Commerce storefronts allowed. This determines how many separate online stores you can operate for business customers.",
  },
  {
    header: "B2C Commerce GMV",
    topic: "setting/force.com/orgValue.B2CCommInternalGmvSum",
    group: "Usage Entitlements",
    body: "Defines the Gross Merchandise Value (GMV) limit for B2C Commerce. This helps track and manage the total value of goods sold through your B2C storefronts.",
  },
  {
    header: "B2B Commerce Total Products",
    topic: "setting/force.com/orgValue.B2bcommPkgProductCountTotal",
    group: "Usage Entitlements",
    body: "Sets the maximum number of products that can be managed in B2B Commerce. This limits the total catalog size across all your B2B storefronts.",
  },
  {
    header: "Content Delivery Network (CDN) Bandwidth Limit in Terabytes (TB)",
    topic: "setting/force.com/orgValue.CommunitiesCDNBandwidth",
    group: "Usage Entitlements",
    body: "Determines the maximum CDN bandwidth usage allowed, measured in terabytes. This helps manage data transfer for your community and site content delivery.",
  },
  {
    header: "B2B Commerce Orders Placed",
    topic: "setting/force.com/orgValue.B2bcommPkgOrdersPlacedDaily",
    group: "Usage Entitlements",
    body: "Specifies the maximum number of orders that can be placed daily in B2B Commerce. This helps manage the transaction volume for your B2B storefronts.",
  },
  {
    header: "Service Document generations per Month",
    topic: "setting/force.com/orgValue.ServiceRptGenMonthlyLimit",
    group: "Usage Entitlements",
    body: "Defines the maximum number of service documents that can be generated per month. This limits how many reports or documents can be created for service-related activities.",
  },
  {
    header: "Service Documents generation base limit",
    topic: "setting/force.com/orgValue.ServiceRptGenBaseLimit",
    group: "Usage Entitlements",
    body: "Sets the base limit for service document generation. This establishes a minimum number of service documents that can be generated, regardless of other factors.",
  },

  {
    header: "B2B Buyer Permission Set One Seat",
    topic: "B2BBuyerPsl",
    group: "PermissionSet Licenses",
    body: "Grants access to B2B Commerce features for buyers, allowing them to make purchases and interact with the B2B storefront.",
    loaded: true,
  },
  {
    header: "Commerce User",
    topic: "CommerceUserPsl",
    group: "PermissionSet Licenses",
    body: "Provides permissions for users to manage and operate Commerce Cloud functionalities within Salesforce.",
    loaded: true,
  },
  {
    header: "B2B Buyer Manager Permission Set One Seat",
    topic: "B2BBuyerManagerPsl",
    group: "PermissionSet Licenses",
    body: "Grants additional permissions for B2B Commerce buyers with managerial responsibilities, allowing them to oversee purchasing activities.",
    loaded: true,
  },
  {
    header: "Loyalty Analytics Apps",
    topic: "LoyaltyAnalyticsPlusPsl",
    group: "PermissionSet Licenses",
    body: "Enables access to analytics applications specifically designed for loyalty program management and analysis.",
    loaded: true,
  },
  {
    header: "Manufacturing Advanced Account Forecast Psl",
    topic: "ManufacturingAdvancedAccountForecastPsl",
    group: "PermissionSet Licenses",
    body: "Provides advanced forecasting capabilities for manufacturing accounts, allowing for more accurate predictions and planning.",
    loaded: true,
  },
  {
    header: "Manufacturing Advanced Account Forecast For Community Psl",
    topic: "ManufacturingAdvAccForecastForCmtyPsl",
    group: "PermissionSet Licenses",
    body: "Extends advanced forecasting capabilities for manufacturing accounts to community users.",
    loaded: true,
  },
  {
    header: "CGC Processing Services Register Psl",
    topic: "CGCProcessingServicesRegisterPsl",
    group: "PermissionSet Licenses",
    body: "Provides access to CGC (Consumer Goods Cloud) processing services registration features.",
    loaded: true,
  },
  {
    header: "Slack Service User",
    topic: "SlackServiceUserPsl",
    group: "PermissionSet Licenses",
    body: "Grants permissions for integration between Salesforce and Slack, enabling automated processes and notifications.",
    loaded: true,
  },
  {
    header: "Program Based Business Psl for Manufacturing Cloud",
    topic: "ManufacturingProgramBasedBusinessPsl",
    group: "PermissionSet Licenses",
    body: "Enables access to program-based business features within Manufacturing Cloud.",
    loaded: true,
  },
  {
    header: "Commerce Admin Permission Set License Seat",
    topic: "CommerceAdminUserPsl",
    group: "PermissionSet Licenses",
    body: "Grants administrative permissions for managing Commerce Cloud within Salesforce.",
    loaded: true,
  },
  {
    header: "Commerce Merchandiser User Permission Set License Seat",
    topic: "CommerceMerchandiserUserPsl",
    group: "PermissionSet Licenses",
    body: "Provides access to merchandising features within Commerce Cloud for product management and cataloging.",
    loaded: true,
  },
  {
    header: "B2B Commerce",
    topic: "B2BCommerce_B2BCommerceAdminPsl",
    group: "PermissionSet Licenses",
    body: "Grants administrative access to B2B Commerce features for managing the B2B storefront and related processes.",
    loaded: true,
  },
  {
    header: "CRM Analytics Plus",
    topic: "EinsteinAnalyticsPlusPsl",
    group: "PermissionSet Licenses",
    body: "Provides access to advanced analytics features powered by Einstein, offering AI-driven insights and predictions.",
    loaded: true,
  },
  {
    header: "Document Checklist",
    topic: "DocumentChecklistPsl",
    group: "PermissionSet Licenses",
    body: "Enables the use of document checklists for tracking and managing required documentation.",
    loaded: true,
  },
  {
    header: "Lightning Direct Store Delivery Psl",
    topic: "LightningDirectStoreDeliveryPsl",
    group: "PermissionSet Licenses",
    body: "Provides access to features for managing direct store delivery processes in Lightning Experience.",
    loaded: true,
  },
  {
    header: "Admissions Connect",
    topic: "Salesforce_org_RecruitingAndAdmissionsPsl",
    group: "PermissionSet Licenses",
    body: "Grants access to features for managing student recruitment and admissions processes in educational institutions.",
    loaded: true,
  },
  {
    header: "Grants Management",
    topic: "Salesforce_org_GrantsManagementPsl",
    group: "PermissionSet Licenses",
    body: "Enables access to features for managing grant applications, awards, and reporting processes.",
    loaded: true,
  },
  {
    header: "Visual Remote Assistant",
    topic: "TechSee_RemoteVideoAssistancePsl",
    group: "PermissionSet Licenses",
    body: "Provides access to visual remote assistance features for providing customer support.",
    loaded: true,
  },
  {
    header: "Analytics View Only Embedded App",
    topic: "AnalyticsViewOnlyEmbeddedAppPsl",
    group: "PermissionSet Licenses",
    body: "Grants view-only access to embedded analytics applications within Salesforce.",
    loaded: true,
  },
  {
    header: "Manufacturing Sales Agreements For Community Psl",
    topic: "ManufacturingSalesAgreementsForCmtyPsl",
    group: "PermissionSet Licenses",
    body: "Extends sales agreement features for manufacturing to community users.",
    loaded: true,
  },
  {
    header: "Customer Experience Analytics Apps",
    topic: "InsightsCustomerExperienceAnalyticsPsl",
    group: "PermissionSet Licenses",
    body: "Provides access to analytics applications focused on customer experience insights and metrics.",
    loaded: true,
  },
  {
    header: "Einstein Search",
    topic: "MySearchPsl",
    group: "PermissionSet Licenses",
    body: "Enables AI-powered search capabilities within Salesforce, providing more relevant and personalized search results.",
    loaded: true,
  },
  {
    header: "Salesforce CPQ AA License",
    topic: "SalesforceCPQ_CPQAAPerm",
    group: "PermissionSet Licenses",
    body: "Grants access to advanced approval features within Salesforce CPQ (Configure, Price, Quote).",
    loaded: true,
  },
  {
    header: "Salesforce CPQ License",
    topic: "SalesforceCPQ_CPQStandardPerm",
    group: "PermissionSet Licenses",
    body: "Provides access to standard Configure, Price, Quote (CPQ) features for complex product configurations and quote generation.",
    loaded: true,
  },
  {
    header: "Conga Quote Generation for Salesforce CPQ",
    topic: "Conga_CongaQuoteGenerationSalesforceCPQ",
    group: "PermissionSet Licenses",
    body: "Enables the use of Conga's quote generation features integrated with Salesforce CPQ.",
    loaded: true,
  },
  {
    header: "Manufacturing Account Forecast Psl",
    topic: "ManufacturingAccountForecastPsl",
    group: "PermissionSet Licenses",
    body: "Provides access to account forecasting features specific to the manufacturing industry.",
    loaded: true,
  },
  {
    header: "Manufacturing Analytics Apps",
    topic: "InsightsManufacturingAnalyticsPsl",
    group: "PermissionSet Licenses",
    body: "Grants access to analytics applications tailored for manufacturing industry insights and metrics.",
    loaded: true,
  },
  {
    header: "Manufacturing Sales Agreements Psl",
    topic: "ManufacturingSalesAgreementsPsl",
    group: "PermissionSet Licenses",
    body: "Enables access to features for managing sales agreements specific to the manufacturing industry.",
    loaded: true,
  },
  {
    header: "Action Plans",
    topic: "ActionPlansPsl",
    group: "PermissionSet Licenses",
    body: "Provides access to create and manage action plans for various Salesforce objects.",
    loaded: true,
  },
  {
    header: "Lightning Retail Execution Plus Psl",
    topic: "LightningRetailExecutionPlusPsl",
    group: "PermissionSet Licenses",
    body: "Grants access to advanced retail execution features in Lightning Experience.",
    loaded: true,
  },
  {
    header: "Workplace Command Center",
    topic: "WorkplaceCommandCenterPsl",
    group: "PermissionSet Licenses",
    body: "Enables access to a centralized command center for managing workplace-related processes and information.",
    loaded: true,
  },
  {
    header: "Accounting Subledger Growth",
    topic: "Salesforce_org_AccountingSubledgerPsl",
    group: "PermissionSet Licenses",
    body: "Provides access to advanced accounting subledger features for financial management and reporting.",
    loaded: true,
  },
  {
    header: "Manufacturing Account Manager Targets Psl",
    topic: "ManufacturingAccountManagerTargetsPsl",
    group: "PermissionSet Licenses",
    body: "Enables access to features for setting and managing account manager targets in the manufacturing industry.",
    loaded: true,
  },
  {
    header: "Nonprofit Cloud Case Management",
    topic: "Salesforce_org_NonprofitCloudCaseManagementPsl",
    group: "PermissionSet Licenses",
    body: "Grants access to case management features tailored for nonprofit organizations.",
    loaded: true,
  },
  {
    header: "Industries Visit",
    topic: "IndustriesVisitPsl",
    group: "PermissionSet Licenses",
    body: "Provides access to visit management features across various industries.",
    loaded: true,
  },
  {
    header: "SFDO Insights Data Integrity Addon Contacts",
    topic: "Salesforce_org_SFDOInsightsDataIntegrity1000ContactsPsl",
    group: "PermissionSet Licenses",
    body: "Enables additional data integrity features for contacts in Salesforce.org implementations.",
    loaded: true,
  },
  {
    header: "SFDO Insights Data Integrity",
    topic: "Salesforce_org_SFDOInsightsDataIntegrityBasePsl",
    group: "PermissionSet Licenses",
    body: "Provides access to base data integrity features for Salesforce.org implementations.",
    loaded: true,
  },
  {
    header: "Sales Console User",
    topic: "SalesConsoleUser",
    group: "PermissionSet Licenses",
    body: "Grants access to the Sales Console, a specialized interface designed for high-velocity sales environments.",
    loaded: true,
  },
  {
    header: "Orders Platform",
    topic: "ContractsOrdersProductsPsl",
    group: "PermissionSet Licenses",
    body: "Enables access to order management features within the Salesforce platform.",
    loaded: true,
  },
  {
    header: "Company Community for Force.com",
    topic: "CompanyCommunityPsl",
    group: "PermissionSet Licenses",
    body: "Provides access to community features for internal company use on the Force.com platform.",
    loaded: true,
  },
  {
    header: "Work.com Rewards",
    topic: "WorkDotComRewardsPsl",
    group: "PermissionSet Licenses",
    body: "Enables access to employee recognition and rewards features within Work.com.",
    loaded: true,
  },
  {
    header: "Analytics Platform",
    topic: "InsightsBuilderPsl",
    group: "PermissionSet Licenses",
    body: "Grants access to create and customize analytics applications and dashboards.",
    loaded: true,
  },
  {
    header: "SOS User",
    topic: "SosUserPsl",
    group: "PermissionSet Licenses",
    body: "Provides access to SOS (Service Over Shoulder) features for video-based customer support.",
    loaded: true,
  },
  {
    header: "Analytics Cloud Explorer",
    topic: "InsightsExplorerPsl",
    group: "PermissionSet Licenses",
    body: "Enables users to explore and interact with analytics data and dashboards.",
    loaded: true,
  },
  {
    header: "Sales User",
    topic: "SalesUserPsl",
    group: "PermissionSet Licenses",
    body: "Grants access to core sales features and functionalities within Salesforce.",
    loaded: true,
  },
  {
    header: "Service User",
    topic: "ServiceUserPsl",
    group: "PermissionSet Licenses",
    body: "Provides access to core service and support features within Salesforce.",
    loaded: true,
  },
  {
    header: "Lightning Console",
    topic: "LightningConsole",
    group: "PermissionSet Licenses",
    body: "Enables access to the Lightning Console interface for streamlined workflow management.",
    loaded: true,
  },
  {
    header: "Standard Einstein Activity Capture User",
    topic: "StandardEinsteinActivityCapturePsl",
    group: "PermissionSet Licenses",
    body: "Grants access to Einstein Activity Capture for automatically logging emails and events.",
    loaded: true,
  },
  {
    header: "Analytics Template Administration",
    topic: "InsightsInboxAdminAnalyticsPsl",
    group: "PermissionSet Licenses",
    body: "Provides administrative access to manage analytics templates and applications.",
    loaded: true,
  },
  {
    header: "Identity Connect",
    topic: "IdentityConnect",
    group: "PermissionSet Licenses",
    body: "Enables integration between Salesforce and external identity providers for enhanced user management.",
    loaded: true,
  },
  {
    header: "Survey Creator User - 1 Seats",
    topic: "SurveyCreatorPsl",
    group: "PermissionSet Licenses",
    body: "Grants access to create and manage surveys within Salesforce.",
    loaded: true,
  },
  {
    header: "Field Service Mobile",
    topic: "FieldServiceMobilePsl",
    group: "PermissionSet Licenses",
    body: "Provides access to mobile field service features for on-the-go workforce management.",
    loaded: true,
  },
  {
    header: "Field Service Scheduling",
    topic: "FieldServiceSchedulingPsl",
    group: "PermissionSet Licenses",
    body: "Enables access to scheduling features for field services",
    loaded: true,
  },
  {
    header: "Field Service Standard",
    topic: "FieldServiceStandardPsl",
    group: "PermissionSet Licenses",
    body: "A Field Service Standard License grants the legal right to perform and manage on-site service and maintenance tasks according to established industry standards",
    loaded: true,
  },
  {
    header: "Field Service Dispatcher",
    topic: "FieldServiceDispatcherPsl",
    group: "PermissionSet Licenses",
    body: "A field service dispatcher license certifies individuals to coordinate and manage service technicians' schedules, ensuring timely and efficient field operations",
    loaded: true,
  },
  {
    header: "B2B Commerce Buyer License Seats",
    topic: "CommerceBuyerPsg",
    group: "PermissionSet Licenses",
    body: "A B2B commerce buyer license seat is a subscription allowing a single user to access and purchase products or services on a B2B e-commerce platform",
    loaded: true,
  },
  {
    header: "B2B Enhanced Buyer Permission Sets License Seats",
    topic: "B2BEnhancedBuyerPsl",
    group: "PermissionSet Licenses",
    body: "B2B enhanced buyer permission sets license seats: streamline access control for business purchases",
    loaded: true,
  },
  {
    header: "Enablement Lite",
    topic: "EnablementLitePsl",
    group: "PermissionSet Licenses",
    body: "The Enablement Lite License is a limited software usage agreement that grants basic access and functionality with fewer features and lower costs compared to a full license",
    loaded: true,
  },
  {
    header: "Intelligent Document Workspace",
    topic: "IntelligentDocumentWorkspacePsl",
    group: "PermissionSet Licenses",
    body: "An intelligent document workspace license provides access to advanced tools for creating, managing, and collaborating on documents using AI-powered features",
    loaded: true,
  },
  {
    header: "Group Membership",
    topic: "GroupMembershipPsl",
    group: "PermissionSet Licenses",
    body: "A group membership license grants access and benefits to multiple users within an organization or group under a single agreement",
    loaded: true,
  },
  {
    header: "Commerce Reorder Portal Inviter License Seats",
    topic: "CommerceReorderPortalInviterPsl",
    group: "PermissionSet Licenses",
    body: "A commerce reorder portal that manages and invites licensed seats for streamlined procurement",
    loaded: true,
  },
  {
    header: "ContextService Admin Psl",
    topic: "ContextServiceAdminPsl",
    group: "PermissionSet Licenses",
    body: "A context service admin PSL license manages and oversees the provisioning, configuration, and administration of context-aware services within a given environment",
    loaded: true,
  },
  {
    header: "AI Accelerator with Scoring Framework",
    topic: "AIAcceleratorPsl",
    group: "PermissionSet Licenses",
    body: "AI Accelerator: A robust framework providing scoring and licensing capabilities for enhanced AI performance and compliance",
    loaded: true,
  },
  {
    header: "ContextService Runtime Psl",
    topic: "ContextServiceRuntimePsl",
    group: "PermissionSet Licenses",
    body: "The Context Service Runtime PSL License is a legal framework for managing the permissions and restrictions of using context-aware services and runtime environments in software applications",
    loaded: true,
  },
  {
    header: "Automotive Analytics Apps",
    topic: "InsightsAutomotiveAnalyticsPsl",
    group: "PermissionSet Licenses",
    body: "An automotive analytics app license permits users to access and utilize software that analyzes vehicle data for performance, maintenance, and operational insights",
    loaded: true,
  },
  {
    header: "Salesforce Contracts Analytics App",
    topic: "CLMAnalyticsPsl",
    group: "PermissionSet Licenses",
    body: "The Salesforce Contracts Analytics App License enables users to analyze, track, and gain insights from contract data within the Salesforce platform",
    loaded: true,
  },
  {
    header: "Sales Engagement Basic",
    topic: "SalesEngagementBasicPsl",
    group: "PermissionSet Licenses",
    body: "The Sales Engagement Basic license provides essential tools and features for managing and enhancing sales interactions and communications",
    loaded: true,
  },
  {
    header: "Messaging for In-App and Web User",
    topic: "EmbeddedServiceMessagingUserPsl",
    group: "PermissionSet Licenses",
    body: "Unified messaging service for seamless communication across app and web platforms with a user-friendly licensing system",
    loaded: true,
  },
  {
    header: "Salesforce API Integration",
    topic: "SalesforceAPIIntegrationPsl",
    group: "PermissionSet Licenses",
    body: "A Salesforce API integration license allows external applications to access Salesforce data and services via APIs without requiring a full user license",
    loaded: true,
  },
  {
    header: "Commerce Business User",
    topic: "CommerceBusinessUserPsl",
    group: "PermissionSet Licenses",
    body: "A commerce business user license allows a company to legally operate, sell goods or services, and engage in commercial activities",
    loaded: true,
  },
  {
    header: "Chatter Answers User",
    topic: "ChatterAnswersUser",
    group: "Feature Licenses",
    body: "Chatter answers user license is a user agreement outlining the terms and conditions for using Chatter's conversational AI services",
    loaded: true,
  },
  {
    header: "Interaction User",
    topic: "InteractionUser",
    group: "Feature Licenses",
    body: "An Interaction User License permits the user to engage with and utilize a software application or service under specific terms and conditions",
    loaded: true,
  },
  {
    header: "Jigsaw Prospecting User",
    topic: "JigsawProspectingUser",
    group: "Feature Licenses",
    body: "The Jigsaw Prospecting User License provides access to an extensive database of business contact information for targeted sales and marketing efforts",
    loaded: true,
  },
  {
    header: "Knowledge User",
    topic: "KnowledgeUser",
    group: "Feature Licenses",
    body: "A knowledge user license allows individuals or organizations to access, use, and share specific knowledge or intellectual property under defined conditions",
    loaded: true,
  },
  {
    header: "Live Agent User",
    topic: "LiveAgentUser",
    group: "Feature Licenses",
    body: "A live agent user license grants access to real-time customer service software, enabling agents to interact with and assist customers via chat, email, or other communication channels",
    loaded: true,
  },
  {
    header: "Marketing User",
    topic: "MarketingUser",
    group: "Feature Licenses",
    body: "A marketing user license grants specific permissions to individuals, allowing them to access and utilize marketing tools and features within a platform or software",
    loaded: true,
  },
  {
    header: "Offline User",
    topic: "OfflineUser",
    group: "Feature Licenses",
    body: "An offline user license allows software usage without an internet connection, typically requiring periodic validation or manual updates",
    loaded: true,
  },
  {
    header: "Software Foundation Content User",
    topic: "SFContentUser",
    group: "Feature Licenses",
    body: "A Software Foundation content user license grants users specific permissions to use, distribute, and modify content while adhering to predefined terms and conditions",
    loaded: true,
  },
  {
    header: "Site force Contributor User",
    topic: "SiteforceContributorUser",
    group: "Feature Licenses",
    body: "A Site Force Contributor User License allows users to create and manage content, but not administer or configure the Salesforce site",
    loaded: true,
  },
  {
    header: "Siteforce Publisher User",
    topic: "SiteforcePublisherUser",
    group: "Feature Licenses",
    body: "The Site Force Publisher User License grants users access to a Salesforce community for content creation and publication without full CRM capabilities",
    loaded: true,
  },
  {
    header: "Support User",
    topic: "SupportUser",
    group: "Feature Licenses",
    body: "A support user license allows access to technical assistance and customer support services for software or a product",
    loaded: true,
  },
  {
    header: "Work.Com User Feature",
    topic: "WorkDotComUserFeature",
    group: "Feature Licenses",
    body: "Work.com user feature license enables access to comprehensive performance management tools and analytics for streamlined employee evaluation and development",
    loaded: true,
  },
];
